//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int productoID { get; set; }
        public string nombreProducto { get; set; }
        public double PrecioVenta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> descuentoProducto { get; set; }
        public int existenciaProducto { get; set; }
        public Nullable<int> tipopID { get; set; }
        public Nullable<int> PresentacionID { get; set; }
        public Nullable<int> proveedorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual TipoP TipoP { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
